
spring:
  application:
    name: adminservice
  datasource:
    url: jdbc:postgresql://localhost:5444/DraveAuto
    username: postgres
    password: arnold

server:
  port: 8087
  servlet:
    context-path: /api/s7
# config-repo/postgres-common.yml
spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/DraveAuto
    username: postgres
    password: arnold
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
