
spring:
  application:
    name: adminservice
  datasource:
    url: jdbc:postgresql://localhost:5444/DraveAuto
    username: postgres
    password: arnold

server:
  port: 8087
  servlet:
    context-path: /api/s7
